# Generated by Django 3.1.4 on 2021-02-04 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 14, 28, 43, 986633), verbose_name='date published'),
        ),
    ]
